name: jars_mobile
description: Personal Finance Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  firebase_core: ^1.13.1

  firebase_auth: ^3.3.9

  firebase_messaging: ^11.2.8

  # firebase_analytics: ^9.1.0

  flutter_local_notifications: ^9.3.2

  google_sign_in: ^5.2.4

  flutter_svg: ^1.0.3

  flutter_gen: ^4.1.5

  cached_network_image: ^3.2.0

  page_transition: ^2.0.5

  http: ^0.13.4

  provider: ^6.0.2

  flutter_native_splash: ^2.0.5

  shared_preferences: ^2.0.13

  animations: ^2.0.2

  intl: ^0.17.0

  url_launcher: ^6.0.20

  fl_chart: ^0.46.0

  d_chart: ^0.0.4

  flutter_email_sender: ^5.1.0

  tab_indicator_styler: ^2.0.0

  image_picker: ^0.8.4+11

  mime: ^1.0.1

  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner:

  flutter_gen_runner:

  flutter_launcher_icons: "^0.9.2"

  url_strategy: ^0.2.0

# cli: fluttergen -c pubspec.yaml
flutter_icons:
  image_path: "assets/images/jars_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_gen:
  integrations:
    flutter_svg: true

# cli: flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: assets/images/splash_screen_background.png
  branding: assets/images/jars_logo.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    # svgs
    - assets/svgs/google.svg
    - assets/svgs/use_app_time.svg
    - assets/svgs/six_jars_principle.svg
    - assets/svgs/auto_split.svg
    - assets/svgs/jar_necessities.svg
    - assets/svgs/jar_education.svg
    - assets/svgs/jar_investment.svg
    - assets/svgs/jar_play.svg
    - assets/svgs/jar_saving.svg
    - assets/svgs/jar_give.svg
    - assets/svgs/excel.svg
    - assets/svgs/jar.svg

    # images
    - assets/images/jars_logo.png
    - assets/images/account.png
    - assets/images/account_selected.png
    - assets/images/analysis.png
    - assets/images/analysis_selected.png
    - assets/images/home.png
    - assets/images/home_selected.png
    - assets/images/jar.png
    - assets/images/jar_selected.png
    - assets/images/intro_begin.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700